apiVersion: v1
kind: Service
metadata:
  name: goreportcard
  labels:
    app: goreportcard
    app.kubernetes.io/name: goreportcard
    app.kubernetes.io/component: web
spec:
  ports:
    - name: goreportcard
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: goreportcard
    app.kubernetes.io/component: web
  type: LoadBalancer